### ISSUE TITLE
ユーザーのプロフィールを更新する関数を実装する

### ISSUE THREAD

**Issue by ulxsth** [2404-geekcamp/main#33]
# Details
ユーザデータを受け取り、すでに存在する同じidのユーザデータを更新する。

# Approach 
Model層に`update()`を実装した後、Controller層で呼び出して実装する。
Controller層ではHttpRequestを受け取るようにし、リクエストからユーザデータをオブジェクトに再構築して更新するとよさそう。

**Comment by kodainn** [comment]
確認お願い
